config/routes.rb
Rails.application.routes.draw do
  resources :telemetries
  get '/auth/auth0/callback' => 'auth0#callback'
  get '/auth/failure' => 'auth0#failure'
  get '/auth/logout' => 'auth0#logout'
  get '/login' => 'clients#login'

  resources :presences
  resources :positions
  resources :devices do
    member do
      get 'update_presence', to: 'devices#update_presence'
      get 'update_positions', to: 'devices#update_positions'
      get "add_devices", to: "devices#add_devices"
      get "debug", to: "devices#debug"
      get "delete_presence", to: "devices#delete_presence"
    end
    collection do
      get "debugging", to: "devices#debugging"
    end
  end
resources :floors
  resources :buildings
  resources :rooms do
    member do
      get 'update_presence', to: 'rooms#update_presence'
      get "delete_presence", to: "rooms#delete_presence"
    end
  end
  resources :clients do
    member do
      get '/clients/reset', to: 'clients#reset'
      get '/clients/get_all', to: 'clients#get_all'
    end
    resources :rooms
    resources :buildings
    resources :floors
    resources :devices
    resources :positions
    resources :presences
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: 'clients#index'
end

app/models/device.rb
class Device < ApplicationRecord
  self.primary_key = "kio_device_id"
  belongs_to :client
  has_many :presences, foreign_key: 'kio_device_id'

  scope :debugging, -> { where('position_debugging is not null')}
  scope :gateways, -> { where(device_type: "GATEWAY") }
  scope :beams, -> { where(product: "Portal Beam") }
  scope :beacons, -> { where(device_type: "BEACON") }
  scope :tags, -> { where(product: "Asset Tag 2").or(where(product: "Smart Badge")) }

  def name
    self.unique_id + " (" + self.product + ")"
  end
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_device, only: %i[ show edit update destroy
    update_presence update_positions delete_presence debug]

  def debugging
    @client = Client.find(params[:client_id])
    @devices = @client.devices.debugging
  end

  # GET /devices or /devices.json
  def index
    @client = Client.find(params[:client_id])

    # binding.break
    @last_seen = params["last_seen"] || 7
    params["device_type"].blank? ? @device_type = 5 : @device_type = params["device_type"].to_i

    case @device_type
    when 2
      @devices = @client.devices.gateways
    when 3
      @devices = @client.devices.beams
    when 4
      @devices = @client.devices.beacons
    when 5
      @devices = @client.devices.tags
    else
      @devices = @client.devices
    end

    unless @last_seen.nil? || @last_seen.blank?
      ls = DateTime.now
      ls = ls - @last_seen.to_i.days
      @devices = @devices.where("last_seen > ?", ls)
    end
  end

  def update_presence
    PresenceJob.perform_async(@device.client, @device.mac)
    # PresenceService.new.get_presence(@device.client, @device.mac)
    respond_to do |format|
      format.html { redirect_to @device, notice: "Device presence determined." }
      format.json { head :no_content }
    end
  end

  def debug
    DeviceDebugJob.perform_async(@device.client, @device)
    respond_to do |format|
      format.html { redirect_to @device, notice: "Device debug report created." }
      format.json { head :no_content }
    end
  end

  def update_positions
    PositionsService.new.get_positions(@device.client, @device.mac)
    respond_to do |format|
      format.html { redirect_to @device, notice: "Device locations determined." }
      format.json { head :no_content }
    end
  end

  def delete_presence
    @device.presences.destroy_all

    respond_to do |format|
      format.html { redirect_to @device, notice: "Device locations deleted." }
      format.json { head :no_content }
    end
  end

  def add_devices
    @client = Client.find(params[:client_id])

    DeviceJob.perform_async(@client)

    respond_to do |format|
      format.html { redirect_to @client, notice: "Device locations determined." }
      format.json { head :no_content }
    end
  end


  # GET /devices/1 or /devices/1.json
  def show
  end

  # GET /devices/new
  def new
    @device = Device.new
  end

  # GET /devices/1/edit
  def edit
  end

  # POST /devices or /devices.json
  def create
    @device = Device.new(device_params)

    respond_to do |format|
      if @device.save
        format.html { redirect_to device_url(@device), notice: "Device was successfully created." }
        format.json { render :show, status: :created, location: @device }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /devices/1 or /devices/1.json
  def update
    respond_to do |format|
      if @device.update(device_params)
        format.html { redirect_to device_url(@device), notice: "Device was successfully updated." }
        format.json { render :show, status: :ok, location: @device }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /devices/1 or /devices/1.json
  def destroy
    @device.destroy

    respond_to do |format|
      format.html { redirect_to devices_url, notice: "Device was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_device
      @device = Device.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def device_params
      params.require(:device).permit(:client_id, :kio_device_id, :unique_id, :device_type, :model, :product, :firmware, :order_id)
    end
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/views/devices/_device.html.erb
<h2>Device: <%= device.unique_id %></h2>
<div class="row">
  <div class="col">
    <p>
      <strong>Client:</strong>
      <%= link_to device.client.name, device.client %>
    </p>
    <p>
      <strong>Kio device:</strong>
      <%= device.kio_device_id %>
    </p>
    <p>
      <strong>Order ID</strong>
      <%= device.order_id %>
    </p>
  </div>
  <div class="col">
    <p>
      <strong>MAC:</strong>
      <%= device.mac&.downcase %>
    </p>
    <p>
      <strong>Device type:</strong>
      <%= device.device_type %>
    </p>
    <p>
      <strong>Model:</strong>
      <%= device.model %>
    </p>
  </div>
  <div class="col">
    <p>
      <strong>Product:</strong>
      <%= device.product %>
    </p>
    <p>
      <strong>Firmware:</strong>
      <%= device.firmware %>
    </p>
    <p>
      <strong>Battery Level:</strong>
      <%= device.battery_level %>
    </p>
  </div>
  <div class="col">
    <p>
    </p>
  </div>
  <div class="col">
    <p>
      <u>Log into <%= device.client.name %> first..</u>
    </p>
    <p>
      <strong>Device Management Link:</strong>
      <%= link_to device.unique_id,
      "https://app.cloud.us.kontakt.io/device-management/devices/beacon/" +
      device.unique_id + "/general",
      target: "top" %>
    </p>
    <p>
      <strong>Smart Location Link:</strong>
      <%= link_to device.unique_id,
      "https://app.cloud.us.kontakt.io/smart-location/device/" +
      device.unique_id,
      target: "top" %>
    </p>
  </div>
</div>

app/views/devices/_devices_table.html.erb
<div class="container-fluid">
  <h1>Devices</h1>
  <table class="table" id="devices">
    <thead>
      <tr>
        <th>Client</th>
        <th>Mac</th>
        <th>Kio ID</th>
        <th>Unique ID</th>
        <th>Device type</th>
        <th>Last Seen</th>
        <th>Product</th>
        <th>Firmware</th>
        <th>Battery</th>
        <th>Order</th>
      </tr>
    </thead>
    <tbody>
      <% @devices.each do |device| %>
        <tr>
          <td><%= link_to device.client.name, device.client %></td>
          <td><%= device.mac&.downcase %></td>
          <td><%= device.kio_device_id %></td>
          <td><%= link_to device.unique_id, device %></td>
          <td><%= device.device_type %></td>
          <td><%= kio_date_time device.last_seen %></td>
          <td><%= device.product %></td>
          <td><%= device.firmware %></td>
          <td><%= device.battery_level %></td>
          <td><%= device.order_id %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <br>
</div>
<script>
  $(document).ready(function () {
   $('#devices').DataTable({
    "dom": '<"search"f><"pagination"ip>',
    columnDefs: [
      { type: 'date', targets: 5 }
    ],
    pageLength: 50,
    "order": [[5, "desc"]]
   })
  });
</script>

app/views/devices/_form.html.erb
<%= form_with(model: device) do |form| %>
  <% if device.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(device.errors.count, "error") %> prohibited this device from being saved:</h2>
      <ul>
        <% device.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= form.label :client_id, style: "display: block" %>
    <%= form.number_field :client_id %>
  </div>
  <div>
    <%= form.label :kio_device_id, style: "display: block" %>
    <%= form.number_field :kio_device_id %>
  </div>
  <div>
    <%= form.label :unique_id, style: "display: block" %>
    <%= form.text_field :unique_id %>
  </div>
  <div>
    <%= form.label :device_type, style: "display: block" %>
    <%= form.text_field :device_type %>
  </div>
  <div>
    <%= form.label :model, style: "display: block" %>
    <%= form.text_field :model %>
  </div>
  <div>
    <%= form.label :product, style: "display: block" %>
    <%= form.text_field :product %>
  </div>
  <div>
    <%= form.label :firmware, style: "display: block" %>
    <%= form.text_field :firmware %>
  </div>
  <div>
    <%= form.label :order_id, style: "display: block" %>
    <%= form.text_field :order_id %>
  </div>
  <div>
    <%= form.label :x, style: "display: block" %>
    <%= form.text_field :x %>
  </div>
  <div>
    <%= form.label :y, style: "display: block" %>
    <%= form.text_field :y %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/devices/debugging.html.erb
<h1>Debugging Reports</h1>
<%= render partial: 'devices/devices_table', locals: { devices: @devices } %>

app/views/devices/edit.html.erb
<h1>Editing device</h1>

<%= render "form", device: @device %>

<br>

<div>
  <%= link_to "Show this device", @device %> |
  <%= link_to "Back to devices", devices_path %>
</div>

app/views/devices/index.html.erb
<%= form_tag(client_devices_path(@client), method: 'get') do %>
  <%= label_tag(:last_seen, "Last Seen (days):") %>
  <%= text_field_tag(:last_seen, @last_seen) %>
  <%= select_tag(:device_type,
      options_for_select([['All', 1], ['Gateways', 2],
      ['Portal Beams', 3], ['Beacons', 4], ['Tags', 5]],
      selected: @device_type)) %>
  <%= submit_tag("Filter") %>
<% end %>
<div class="row pt-5">
  <% pie_height = "200px" %>
  <div class="col">
    <h4>Device Types</h4>
    <%= pie_chart @devices.group(:product).count, height: pie_height %>
  </div>
  <div class="col">
    <h4>Firmware</h4>
    <%= pie_chart @devices.group(:firmware).count, height: pie_height %>
  </div>
  <div class="col">
    <h4>Battery Level</h4>
    <%= pie_chart @devices.group(:battery_level).count, height: pie_height %>
  </div>
  <div class="col">
    <h4>Order ID</h4>
    <%= pie_chart @devices.group(:order_id).count, height: pie_height %>
  </div>
</div class="pb-3">
<h4>Last seen</h4>
<%= column_chart @devices.group_by_day(:last_seen).count, height: "100px"  %>
<%= render partial: 'devices_table', locals: { devices: @devices } %>

app/views/devices/new.html.erb
<h1>New device</h1>

<%= render "form", device: @device %>

<br>

<div>
  <%= link_to "Back to devices", devices_path %>
</div>

app/views/devices/show.html.erb
<%= render @device %>
<div>
  <%= link_to "All devices", client_devices_path(@device.client) %>
  <div class="pt-2 text-center">
    <%= link_to "Update presence", update_presence_device_path(@device), class: "btn btn-success"  %>
    <%= link_to "Delete presence data (careful!)", delete_presence_device_path(@device), class: "btn btn-danger" %>
  </div>
</div>
<%= render partial: 'presences/presence_table', locals: { presences: @device.presences } %>
<h3>Device Debugging</h3>
<%= link_to "Debug device", debug_device_path(@device), class: "btn btn-warning"  %>
<p class="pt-2">
  <% unless @device.position_debugging.blank? %>
    <%== simple_format bash_to_html_colors(( @device.position_debugging)) %>
  <% end %>
</p>