config/routes.rb
Rails.application.routes.draw do
  resources :telemetries
  get '/auth/auth0/callback' => 'auth0#callback'
  get '/auth/failure' => 'auth0#failure'
  get '/auth/logout' => 'auth0#logout'
  get '/login' => 'clients#login'

  resources :presences
  resources :positions
  resources :devices do
    member do
      get 'update_presence', to: 'devices#update_presence'
      get 'update_positions', to: 'devices#update_positions'
      get "add_devices", to: "devices#add_devices"
      get "debug", to: "devices#debug"
      get "delete_presence", to: "devices#delete_presence"
    end
    collection do
      get "debugging", to: "devices#debugging"
    end
  end
resources :floors
  resources :buildings
  resources :rooms do
    member do
      get 'update_presence', to: 'rooms#update_presence'
      get "delete_presence", to: "rooms#delete_presence"
    end
  end
  resources :clients do
    member do
      get '/clients/reset', to: 'clients#reset'
      get '/clients/get_all', to: 'clients#get_all'
    end
    resources :rooms
    resources :buildings
    resources :floors
    resources :devices
    resources :positions
    resources :presences
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: 'clients#index'
end

app/models/client.rb
class Client < ApplicationRecord
  has_many :rooms
  has_many :buildings
  has_many :floors, through: :buildings

  has_many :devices
  has_many :presences, through: :devices
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :authenticate_user!, except: [:login]

  before_action :set_client, only: %i[ show edit update destroy reset get_all]

  # GET /clients or /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1 or /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  def reset
    Floor.where(client_id: @client.id).delete_all
    Building.where(client_id: @client.id).delete_all
    Room.where(client_id: @client.id).delete_all
    Device.where(client_id: @client.id).delete_all

    respond_to do |format|
      format.html { redirect_to @client, notice: "Client was successfully reset." }
      format.json { head :no_content }
    end
  end

  def get_all
    SetupJob.perform_async(@client)
    respond_to do |format|
      format.html { redirect_to @client, notice: "Client being set up..." }
      format.json { head :no_content }
    end
  end

  # POST /clients or /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to client_url(@client), notice: "Client was successfully created." }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1 or /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to client_url(@client), notice: "Client was successfully updated." }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1 or /clients/1.json
  def destroy
    @client.destroy

    respond_to do |format|
      format.html { redirect_to clients_url, notice: "Client was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def client_params
      params.require(:client).permit(:name, :api_key, :user, :pass)
    end

end

app/helpers/clients_helper.rb
module ClientsHelper

  def last_updated_date(things)
    if things.order(updated_at: :desc).first.nil?
      return "-"
    else
      return kio_date_time things.order(updated_at: :desc).first.updated_at
    end
  end
end

app/views/clients/_client.html.erb
<div id="<%= dom_id client %>">
  <h2>
    <%= client.name %>
  </h2>

</div>

app/views/clients/_form.html.erb
<%= form_with(model: client) do |form| %>
  <% if client.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
        <% client.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :api_key, style: "display: block" %>
    <%= form.text_field :api_key %>
  </div>

  <div>
    <%= form.label :user, style: "display: block" %>
    <%= form.text_field :user %>
  </div>

  <div>
    <%= form.label :pass, style: "display: block" %>
    <%= form.text_field :pass %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editing client</h1>

<%= render "form", client: @client %>

<br>

<div>
  <%= link_to "Show this client", @client %> |
  <%= link_to "Back to clients", clients_path %>
</div>

app/views/clients/index.html.erb
<div class="container-fluid">
  <h1>Clients</h1>
  <div class="row">
    <div class="col">
      <table class="table">
        <thead>
          <tr>
            <th>Name</th>
            <th>Api key</th>
          </tr>
        </thead>
        <tbody>
          <% @clients.each do |client| %>
            <tr>
              <td><%= link_to client.name, client %></td>
              <td><%= client.api_key %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <br>
      <%= link_to 'New Client', new_client_path, class: "btn btn-primary" %>
    </div>
    <div class="col pt-5">
      <%= render partial: '/buildings/maps', locals: { buildings: Building.all } %>
    </div>
  </div>
</div>

app/views/clients/login.html.erb
<%= button_to 'Login', '/auth/auth0', method: :post, data: { turbo: false } %>

app/views/clients/new.html.erb
<h1>New client</h1>

<%= render "form", client: @client %>

<br>

<div>
  <%= link_to "Back to clients", clients_path %>
</div>

app/views/clients/show.html.erb
<div class="container-fluid">
  <h1><%= @client.name%></h1>
  <table class="table">
    <thead>
      <tr>
        <th>Entity</th>
        <th>Last Updated</th>
        <th>Ago</th>
        <th>Update Now</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>
          <%=
            link_to client_buildings_path(@client) do
              pluralize(@client.buildings.size, "Building")
            end
         %>
        </td>
        <td><%= last_updated_date(@client.buildings) %></td>
        <td><%= time_ago_in_words last_updated_date(@client.buildings) unless last_updated_date(@client.buildings) =="-" %></td>
        <td>-</td>
      </tr>
      <tr>
        <td>
          <%=
            link_to client_floors_path(@client) do
              pluralize(@client.floors.size, "Floor")
            end
         %>
        </td>
        <td><%= last_updated_date(@client.floors) %></td>
        <td><%= time_ago_in_words last_updated_date(@client.floors) unless last_updated_date(@client.buildings) =="-" %></td>
        <td>-</td>
      </tr>
      <tr>
        <td>
          <%=
            link_to client_rooms_path(@client) do
              pluralize(@client.rooms.size, "Room")
            end
         %>
        </td>
        <td><%=  last_updated_date(@client.rooms) %></td>
        <td><%= time_ago_in_words last_updated_date(@client.rooms) unless last_updated_date(@client.rooms) =="-" %></td>
        <td>-</td>
      </tr>
      <tr>
        <td>
          <%=
            link_to client_devices_path(@client) do
              pluralize(@client.devices.size, "Device")
            end
         %>
        </td>
        <td><%= last_updated_date(@client.devices) %></td>
        <td><%= time_ago_in_words last_updated_date(@client.devices) unless last_updated_date(@client.devices) =="-" %></td>
        <td><%= link_to 'Refresh', add_devices_device_path(client_id: @client.id) %></td>
      </tr>
      <tr>
        <td>
          <%=
            link_to client_presences_path(@client) do
              pluralize(@client.presences.size, "Presences")
            end
         %>
        </td>
        <td><%= last_updated_date(@client.devices) %></td>
        <td><%= time_ago_in_words last_updated_date(@client.devices) unless last_updated_date(@client.devices) =="-" %></td>
        <td><%= link_to 'Refresh', add_devices_device_path(client_id: @client.id) %></td>
      </tr>
      <tr>
        <td>
          <%=
            link_to debugging_devices_path(client_id: @client) do
              pluralize(@client.devices.debugging.size, "Position Debugging")
            end
         %>
        </td>
        <td><%= last_updated_date(@client.devices) %></td>
        <td></td>
        <td></td>
      </tr>
    </tbody>
  </table>
  <div class="pt-2 text-center">
    <%= link_to 'New Client', new_client_path, class: "btn btn-primary" %>
    <%= link_to 'Reset Client (Careful)', clients_reset_client_path, class: "btn btn-danger" %>
    <%= link_to 'Get Space / Device Data', clients_get_all_client_path, class: "btn btn-success" %>
  </div>
</div>
<div class="pt-5">
  <%= render partial: '/buildings/maps', locals: { buildings: @client.buildings } %>
</div>