config/routes.rb
Rails.application.routes.draw do
  resources :telemetries
  get '/auth/auth0/callback' => 'auth0#callback'
  get '/auth/failure' => 'auth0#failure'
  get '/auth/logout' => 'auth0#logout'
  get '/login' => 'clients#login'

  resources :presences
  resources :positions
  resources :devices do
    member do
      get 'update_presence', to: 'devices#update_presence'
      get 'update_positions', to: 'devices#update_positions'
      get "add_devices", to: "devices#add_devices"
      get "debug", to: "devices#debug"
      get "delete_presence", to: "devices#delete_presence"
    end
    collection do
      get "debugging", to: "devices#debugging"
    end
  end
resources :floors
  resources :buildings
  resources :rooms do
    member do
      get 'update_presence', to: 'rooms#update_presence'
      get "delete_presence", to: "rooms#delete_presence"
    end
  end
  resources :clients do
    member do
      get '/clients/reset', to: 'clients#reset'
      get '/clients/get_all', to: 'clients#get_all'
    end
    resources :rooms
    resources :buildings
    resources :floors
    resources :devices
    resources :positions
    resources :presences
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: 'clients#index'
end

app/models/building.rb
class Building < ApplicationRecord
  self.primary_key = "kio_building_id"

  belongs_to :client
  has_many :floors, foreign_key: 'kio_building_id'
end

app/controllers/buildings_controller.rb
class BuildingsController < ApplicationController
  before_action :authenticate_user!

  before_action :set_building, only: %i[ show edit update destroy]

  # GET /buildings or /buildings.json
  def index
    @client = Client.find(params[:client_id])

    if @client.nil?
      @buildings = Building.all
    else
      @buildings = Building.where(client_id: @client.id)
    end
  end

  # GET /buildings/1 or /buildings/1.json
  def show
  end

  # GET /buildings/new
  def new
    @building = Building.new
  end

  # GET /buildings/1/edit
  def edit
  end

  # POST /buildings or /buildings.json
  def create
    @building = Building.new(building_params)

    respond_to do |format|
      if @building.save
        format.html { redirect_to building_url(@building), notice: "Building was successfully created." }
        format.json { render :show, status: :created, location: @building }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @building.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /buildings/1 or /buildings/1.json
  def update
    respond_to do |format|
      if @building.update(building_params)
        format.html { redirect_to building_url(@building), notice: "Building was successfully updated." }
        format.json { render :show, status: :ok, location: @building }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @building.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /buildings/1 or /buildings/1.json
  def destroy
    @building.destroy

    respond_to do |format|
      format.html { redirect_to buildings_url, notice: "Building was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_building
      @building = Building.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def building_params
      params.require(:building).permit(:building_id, :name, :address, :client_id, :lat, :lng)
    end
end

app/helpers/buildings_helper.rb
module BuildingsHelper
end

app/views/buildings/_building.html.erb
<div class="row">
  <div class="col">
    <p>
      <strong>Building:</strong>
      <%= building.kio_building_id %>
    </p>
    <p>
      <strong>Name:</strong>
      <%= building.name %>
    </p>
    <p>
      <strong>Address:</strong>
      <%= building.address %>
    </p>
    <p>
      <strong>Client:</strong>
      <%= link_to building.client.name, building.client %>
    </p>
    <p>
      <strong>Floors:</strong>
      <ul>
        <% building.floors.order(:name).each do |floor| %>
          <li><%= link_to floor.name, floor %></li>
        <% end %>
      </ul>
    </p>
  </div>
  <div class="col">
    <%= render partial: 'map', locals: { building: building } %>
  </div>
</div>

app/views/buildings/_form.html.erb
<%= form_with(model: building) do |form| %>
  <% if building.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(building.errors.count, "error") %> prohibited this building from being saved:</h2>

      <ul>
        <% building.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :building_id, style: "display: block" %>
    <%= form.number_field :building_id %>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :address, style: "display: block" %>
    <%= form.text_field :address %>
  </div>

  <div>
    <%= form.label :client_id, style: "display: block" %>
    <%= form.number_field :client_id %>
  </div>

  <div>
    <%= form.label :lat, style: "display: block" %>
    <%= form.text_field :lat %>
  </div>

  <div>
    <%= form.label :lng, style: "display: block" %>
    <%= form.text_field :lng %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/buildings/_map.html.erb
<script src='https://api.mapbox.com/mapbox-gl-js/v2.9.2/mapbox-gl.js'></script>
<link href='https://api.mapbox.com/mapbox-gl-js/v2.9.2/mapbox-gl.css' rel='stylesheet' />
<div data-turbolinks="false" style="height:300px; width:100%; background:#000000" id="kiomap"></div>
<script>
  mapboxgl.accessToken = 'pk.eyJ1IjoidGhlYWxleSIsImEiOiJjajhveWV4cDIwYTg3MnFvM28yMm93YmM4In0.1g8ow7OIKJ8J-4LZbYg3Vg';


  const map = new mapboxgl.Map({
    container: 'kiomap',
    style: 'mapbox://styles/mapbox/streets-v12',
    center: [<%= building.lng%>, <%= building.lat %>],
    zoom: 11
  });

  // Create a new marker.
  const marker = new mapboxgl.Marker()
      .setLngLat([<%= building.lng%>, <%= building.lat %>])
      .addTo(map);

  map.addControl(new mapboxgl.NavigationControl());

  map.on('style.load', () => {
  // Insert the layer beneath any symbol layer.
  const layers = map.getStyle().layers;
  const labelLayerId = layers.find(
  (layer) => layer.type === 'symbol' && layer.layout['text-field']
  ).id;


  });
</script>

app/views/buildings/_maps.html.erb
<% @buildings = buildings %>
<script src='https://api.mapbox.com/mapbox-gl-js/v2.9.2/mapbox-gl.js'></script>
<link href='https://api.mapbox.com/mapbox-gl-js/v2.9.2/mapbox-gl.css' rel='stylesheet' />
<div data-turbolinks="false" style="height:500px; width:100%; background:#000000" id="kiomap"></div>
<script>
  mapboxgl.accessToken = 'pk.eyJ1IjoidGhlYWxleSIsImEiOiJjajhveWV4cDIwYTg3MnFvM28yMm93YmM4In0.1g8ow7OIKJ8J-4LZbYg3Vg';

  const map = new mapboxgl.Map({
    container: 'kiomap',
    center: [-98.5795, 37.7749],

    style: 'mapbox://styles/mapbox/streets-v12',
    zoom: 10
  });
  map.addControl(new mapboxgl.NavigationControl());

  var bounds = new mapboxgl.LngLatBounds();

  <% @buildings.each do |building| %>

     popup = new mapboxgl.Popup({ offset: 25 }).setText(
      'Construction on the Washington Monument began in 1848.'
    );

    var m = new mapboxgl.Marker()
      .setLngLat([<%= building.lng %>, <%= building.lat %>])
      .setPopup(new mapboxgl.Popup({ offset: 50 }).setHTML(
          "<h4><%= building.client.name %>: <%= building.name %></h4>"
        ))
      .addTo(map);

      bounds.extend([<%= building.lng %>, <%= building.lat %>]);



  <% end %>

  map.fitBounds(bounds, {
    maxZoom: 9
    });

      map.on('style.load', () => {
        // Insert the layer beneath any symbol layer.
        const layers = map.getStyle().layers;
        const labelLayerId = layers.find(
        (layer) => layer.type === 'symbol' && layer.layout['text-field']
        ).id;
      });
</script>

app/views/buildings/edit.html.erb
<h1>Editing building</h1>

<%= render "form", building: @building %>

<br>

<div>
  <%= link_to "Show this building", @building %> |
  <%= link_to "Back to buildings", buildings_path %>
</div>

app/views/buildings/index.html.erb
<div class="container-fluid">
  <h1>Buildings</h1>
  <%= render partial: 'maps', locals: { buildings: @buildings } %>
  <table class="table">
    <thead>
      <tr>
        <th>Building</th>
        <th>Address</th>
        <th>Client</th>
        <th>Floors</th>
      </tr>
    </thead>
    <tbody>
      <% @buildings.each do |building| %>
        <tr>
          <td><%= link_to building.name, building %></td>
          <td><%= link_to building.client.name, building.client %></td>
          <td><%= building.address %></td>
          <td><%= link_to building.floors.size.to_s, floors_path(building.floors) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <br>
  <%= link_to 'New Building', new_building_path, class: "btn btn-primary" %>
</div>

app/views/buildings/new.html.erb
<h1>New building</h1>

<%= render "form", building: @building %>

<br>

<div>
  <%= link_to "Back to buildings", buildings_path %>
</div>

app/views/buildings/show.html.erb
<%= render @building %>
<div>
  <%=
    link_to client_buildings_path(@building.client) do
      pluralize(@building.client.buildings.size, "Building")
    end
    %>
</div>