config/routes.rb
Rails.application.routes.draw do
  resources :telemetries
  get '/auth/auth0/callback' => 'auth0#callback'
  get '/auth/failure' => 'auth0#failure'
  get '/auth/logout' => 'auth0#logout'
  get '/login' => 'clients#login'

  resources :presences
  resources :positions
  resources :devices do
    member do
      get 'update_presence', to: 'devices#update_presence'
      get 'update_positions', to: 'devices#update_positions'
      get "add_devices", to: "devices#add_devices"
      get "debug", to: "devices#debug"
      get "delete_presence", to: "devices#delete_presence"
    end
    collection do
      get "debugging", to: "devices#debugging"
    end
  end
resources :floors
  resources :buildings
  resources :rooms do
    member do
      get 'update_presence', to: 'rooms#update_presence'
      get "delete_presence", to: "rooms#delete_presence"
    end
  end
  resources :clients do
    member do
      get '/clients/reset', to: 'clients#reset'
      get '/clients/get_all', to: 'clients#get_all'
    end
    resources :rooms
    resources :buildings
    resources :floors
    resources :devices
    resources :positions
    resources :presences
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: 'clients#index'
end

app/models/room.rb
class Room < ApplicationRecord
  self.primary_key = "kio_room_id"
  belongs_to :client
  belongs_to :floor, foreign_key: "kio_floor_id"
  has_many :presences, foreign_key: 'kio_room_id'

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_room, only: %i[ show edit update destroy
      update_presence delete_presence ]

  # GET /rooms or /rooms.json
  def index
      @client = Client.find(params[:client_id])
      @pagy, @rooms = pagy(Room.where(client_id: @client.id))
  end

  # GET /rooms/1 or /rooms/1.json
  def show
  end

  def update_presence
    PresenceService.new.get_presence_by_room(@room.client, @room.kio_room_id)
    respond_to do |format|
      format.html { redirect_to @room, notice: "Room presence determined." }
      format.json { head :no_content }
    end
  end

  def delete_presence
    Presence.where(kio_room_id: @room.kio_room_id).destroy_all
    respond_to do |format|
      format.html { redirect_to @room, notice: "Room presence deleted." }
      format.json { head :no_content }
    end
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms or /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to room_url(@room), notice: "Room was successfully created." }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1 or /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to room_url(@room), notice: "Room was successfully updated." }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def room_params
      params.require(:room).permit(:client_id, :room_id, :name, :floor_name, :building_name)
    end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
<%= form_with(model: room) do |form| %>
  <% if room.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>
      <ul>
        <% room.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= form.label :client_id, style: "display: block" %>
    <%= form.number_field :client_id %>
  </div>
  <div>
    <%= form.label :room_id, style: "display: block" %>
    <%= form.number_field :room_id %>
  </div>
  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :floor_name, style: "display: block" %>
    <%= form.text_field :floor_name %>
  </div>
  <div>
    <%= form.label :building_name, style: "display: block" %>
    <%= form.text_field :building_name %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/rooms/_room.html.erb
<div class="row">
  <div class="col">
    <div id="<%= dom_id room %>">
      <h3>Room: <%= room.kio_room_id.to_s %></h3>
      <p>
        <strong>Client:</strong>
        <%= link_to room.client.name, room.client %>
      </p>
      <p>
        <strong>Room:</strong>
        <%= room.kio_room_id %>
      </p>
      <p>
        <strong>Name:</strong>
        <%= room.name %>
      </p>
      <p>
        <strong>Floor name:</strong>
        <%= room.floor.name %>
      </p>
      <p>
        <strong>Building name:</strong>
        <%= room.floor.building.name %>
      </p>
    </div>
  </div>
  <div class="col">
    <h4>Infrastructure</h4>
  </div>
</div>

app/views/rooms/edit.html.erb
<h1>Editing room</h1>

<%= render "form", room: @room %>

<br>

<div>
  <%= link_to "Show this room", @room %> |
  <%= link_to "Back to rooms", rooms_path %>
</div>

app/views/rooms/index.html.erb
<div class="container-fluid">
  <h1>Rooms</h1>
  <table class="table">
    <thead>
      <tr>
        <th>Client</th>
        <th>Room #</th>
        <th>Name</th>
        <th>Floor</th>
        <th>Building</th>
      </tr>
    </thead>
    <tbody>
      <% @rooms.each do |room| %>
        <tr>
          <td><%= link_to room.client.name, room.client %></td>
          <td><%= room.kio_room_id %></td>
          <td><%= link_to room.name, room %></td>
          <td><%= link_to room.floor.name, room.floor %></td>
          <td><%= link_to room.floor.building.name, room.floor.building %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<div class="pt-4">
  <%== pagy_bootstrap_combo_nav_js(@pagy) %>
</div>

app/views/rooms/new.html.erb
<h1>New room</h1>

<%= render "form", room: @room %>

<br>

<div>
  <%= link_to "Back to rooms", rooms_path %>
</div>

app/views/rooms/show.html.erb
<%= render @room %>
<div>
  <%= link_to "Edit this room", edit_room_path(@room) %> |
  <%= link_to "Back to rooms", client_rooms_path(@room.client) %>
  <div class="pt-3 text-center">
    <%= link_to "Update presence", update_presence_room_path(@room), class: "btn btn-success" %>
    <%= link_to "Delete presence data (careful!)", delete_presence_room_path(@room), class: "btn btn-danger" %>
  </div>
</div>
<%= render partial: 'presences/presence_table', locals: { presences: @room.presences } %>